services:
  - type: web
    name: migration-osint-dashboard
    runtime: python

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      gunicorn dashboard.app:app

    healthCheckPath: /health

    autoDeploy: true
